In [50]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [51]:
data=pd.read_csv('churn_dataset_400.csv')
data.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15630000,Verma,424,Spain,Male,61,8,188234.37,4,0,1,42300.58,0
1,15630001,Nair,578,Spain,Male,41,3,105773.61,3,1,1,39731.86,1
2,15630002,Chatterjee,684,France,Male,67,1,67491.11,4,1,0,33955.10,0
3,15630003,Verma,837,France,Male,23,4,155402.56,3,1,1,86343.24,0
4,15630004,Mehta,380,Spain,Female,65,7,80385.48,4,0,0,24381.33,0

In [52]:
data=data.drop(['CustomerId','Surname'],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,424,Spain,Male,61,8,188234.37,4,0,1,42300.58,0
1,578,Spain,Male,41,3,105773.61,3,1,1,39731.86,1
2,684,France,Male,67,1,67491.11,4,1,0,33955.10,0
3,837,France,Male,23,4,155402.56,3,1,1,86343.24,0
4,380,Spain,Female,65,7,80385.48,4,0,0,24381.33,0

In [53]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,424,Spain,1,61,8,188234.37,4,0,1,42300.58,0
1,578,Spain,1,41,3,105773.61,3,1,1,39731.86,1
2,684,France,1,67,1,67491.11,4,1,0,33955.10,0
3,837,France,1,23,4,155402.56,3,1,1,86343.24,0
4,380,Spain,0,65,7,80385.48,4,0,0,24381.33,0

In [54]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
one_hot_encoder_geo = OneHotEncoder()
geo_encoder = one_hot_encoder_geo.fit_transform(data[['Geography']])
one_hot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_India',
       'Geography_Spain'], dtype=object)

In [55]:
one_hot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_India',
       'Geography_Spain'], dtype=object)

In [56]:
geo_encoded_data=pd.DataFrame(geo_encoder.toarray(),columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_data.head()

   Geography_France  Geography_Germany  Geography_India  Geography_Spain
0               0.0                0.0              0.0              1.0
1               0.0                0.0              0.0              1.0
2               1.0                0.0              0.0              0.0
3               1.0                0.0              0.0              0.0
4               0.0                0.0              0.0              1.0

In [57]:
data=pd.concat([data,geo_encoded_data],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_India,Geography_Spain
0,424,Spain,1,61,8,188234.37,4,0,1,42300.58,0,0.0,0.0,0.0,1.0
1,578,Spain,1,41,3,105773.61,3,1,1,39731.86,1,0.0,0.0,0.0,1.0
2,684,France,1,67,1,67491.11,4,1,0,33955.10,0,1.0,0.0,0.0,0.0
3,837,France,1,23,4,155402.56,3,1,1,86343.24,0,1.0,0.0,0.0,0.0
4,380,Spain,0,65,7,80385.48,4,0,0,24381.33,0,0.0,0.0,0.0,1.0

In [58]:
X = data.drop(['Exited'], axis=1)
y = data['Exited']

# DROP original categorical column
X = X.drop('Geography', axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [59]:
X_train.dtypes

CreditScore            int64
Gender                 int64
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Geography_France     float64
Geography_Germany    float64
Geography_India      float64
Geography_Spain      float64
dtype: object

In [60]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [61]:
X_train

array([[ 0.1589415 ,  1.        ,  0.49073793, ..., -0.62876771,
        -0.531085  , -0.56195149],
       [ 0.32951518, -1.        , -0.95196601, ...,  1.59041245,
        -0.531085  , -0.56195149],
       [ 1.55195986, -1.        ,  1.2120899 , ..., -0.62876771,
         1.88293774, -0.56195149],
       ...,
       [ 1.01891712, -1.        , -0.75523366, ..., -0.62876771,
         1.88293774, -0.56195149],
       [-0.97821635, -1.        ,  1.60555462, ..., -0.62876771,
        -0.531085  ,  1.77951304],
       [-0.87871503, -1.        ,  0.16285067, ..., -0.62876771,
         1.88293774, -0.56195149]])

In [62]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [63]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_India,Geography_Spain
0,424,Spain,1,61,8,188234.37,4,0,1,42300.58,0,0.0,0.0,0.0,1.0
1,578,Spain,1,41,3,105773.61,3,1,1,39731.86,1,0.0,0.0,0.0,1.0
2,684,France,1,67,1,67491.11,4,1,0,33955.10,0,1.0,0.0,0.0,0.0
3,837,France,1,23,4,155402.56,3,1,1,86343.24,0,1.0,0.0,0.0,0.0
4,380,Spain,0,65,7,80385.48,4,0,0,24381.33,0,0.0,0.0,0.0,1.0

In [64]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)

In [65]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [66]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

/Users/niyatisingh/Downloads/ada/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [67]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
import tensorflow
opt =tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy
loss

keras.src.losses.losses.BinaryCrossentropy

In [69]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#compile the model

In [70]:
#set up tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir="log/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [71]:
#set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [72]:
##train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorboard_callback,early_stopping_callback]
)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 66ms/step - accuracy: 0.5067 - loss: 0.7405 - val_accuracy: 0.5800 - val_loss: 0.6897
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5500 - loss: 0.6813 - val_accuracy: 0.5800 - val_loss: 0.6801
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5800 - loss: 0.6721 - val_accuracy: 0.5500 - val_loss: 0.6827
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5800 - loss: 0.6687 - val_accuracy: 0.5500 - val_loss: 0.6853
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5900 - loss: 0.6678 - val_accuracy: 0.5500 - val_loss: 0.6880
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5933 - loss: 0.6685 - val_accuracy: 0.5600 - val_loss: 0.6930
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5900 - loss: 0.6678 - val_accuracy: 0.5400 - val_loss: 0.6969
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5967 - loss: 0.6672 - val_accuracy: 0.5500 - val_loss: 0.6932
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6067 - loss: 0.6669 - val_accuracy: 0.5600 - val_loss: 0.6919
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5967 - loss: 0.6687 - val_accuracy: 0.5400 - val_loss: 0.6877
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6000 - loss: 0.6686 - val_accuracy: 0.5500 - val_loss: 0.6856
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5933 - loss: 0.6682 - val_accuracy: 0.5400 - val_loss: 0.6851

In [73]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [74]:
##load tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [91]:
%tensorboard --logdir log

Reusing TensorBoard on port 6009 (pid 21869), started 0:00:21 ago. (Use '!kill 21869' to kill it.)